CREATE TABLE countries (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE family (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE types (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    family_id BIGINT NOT NULL,
    FOREIGN KEY (family_id) REFERENCES family(id) ON DELETE CASCADE
);

CREATE TABLE animals (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    family_id BIGINT NOT NULL,
    type_id BIGINT NOT NULL,
    gender VARCHAR(10) NOT NULL,
    country_id BIGINT NOT NULL,
    arrival_date DATE NOT NULL,
    photo_url VARCHAR(255),
    FOREIGN KEY (family_id) REFERENCES family(id) ON DELETE CASCADE,
    FOREIGN KEY (type_id) REFERENCES types(id) ON DELETE CASCADE,
    FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE CASCADE
);
